name: Updater!
on:
  push:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  linux:
    name: Check for new Launcher versions
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Running updatemc.sh
      run: ./updatemc.sh
